//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class инвентаризация_склада
    {
        public int ID_инвентаризация_склада { get; set; }
        public System.DateTime дата_инвентаризации { get; set; }
        public int ID_склада { get; set; }
        public int ID_товара { get; set; }
        public int расчетный_остаток { get; set; }
        public int фактический_остаток { get; set; }
        public int ID_сотрудник { get; set; }
    
        public virtual склад склад { get; set; }
        public virtual сотрудник сотрудник { get; set; }
        public virtual товары товары { get; set; }
    }
}
