//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class приемка_товара
    {
        public int ID_приемка_товара { get; set; }
        public int ID_товара { get; set; }
        public int ID_статуса_качества_товара { get; set; }
        public int количество_поступления { get; set; }
        public int количество_принятого_товара { get; set; }
        public int ID_сотрудник { get; set; }
    
        public virtual сотрудник сотрудник { get; set; }
        public virtual статус_качества_товара статус_качества_товара { get; set; }
        public virtual товары товары { get; set; }
    }
}
