//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class товары
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public товары()
        {
            this.инвентаризация_склада = new HashSet<инвентаризация_склада>();
            this.приемка_товара = new HashSet<приемка_товара>();
            this.товары_на_складе = new HashSet<товары_на_складе>();
        }
    
        public int ID_товара { get; set; }
        public string артикул { get; set; }
        public string наименование_товара { get; set; }
        public string фото { get; set; }
        public int ID_категории_товара { get; set; }
        public int ID_пола { get; set; }
        public int ID_размера_одежды { get; set; }
        public int ID_цвета { get; set; }
        public double цена { get; set; }
        public string описание { get; set; }
        public string состав { get; set; }
        public int ID_поставщиков { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<инвентаризация_склада> инвентаризация_склада { get; set; }
        public virtual категория_товара категория_товара { get; set; }
        public virtual пол пол { get; set; }
        public virtual поставщики поставщики { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<приемка_товара> приемка_товара { get; set; }
        public virtual размеры размеры { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<товары_на_складе> товары_на_складе { get; set; }
        public virtual цвет цвет { get; set; }
    }
}
